site_name: Bayti Lab
site_url: https://blog.adoucheali.fr
site_author: Ali Adouche
site_description: >-
  Mes articles autour de java, angular et du devops

repo_name: AdoucheAli/bayti-lab
repo_url: https://github.com/AdoucheAli/bayti-lab

edit_uri: edit/main/docs/

copyright: Copyright &copy; 2023 Ali Adouche

nav:
  - Bayti: index.md
  - Backend: 
    - backend/index.md
  - Frontend: 
    - frontend/index.md
  - Linux: 
    - linux/index.md
    - Multipass:
        - linux/multipass/index.md
  - Container: 
    - container/index.md
  - Kubernetes: 
    - kubernetes/index.md
  - Tags: tags.md

theme:
  name: material
  custom_dir: overrides
  language: fr

  font:
    text: Roboto
    code: Roboto Mono

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: red
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  favicon: assets/favicon.png

  icon:
    logo: logo
    
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css: fontawesome/brands/css3
      linux: fontawesome/brands/linux

    repo: fontawesome/brands/github
    #edit: material/pencil 
    #view: material/eye

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips

    - header.autohide

    - navigation.path
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

    - search.highlight
    - search.share
    - search.suggest

    - toc.follow
    # - toc.integrate si on l'active, on n'aura pas le table of contents à droite

markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: ⚓︎
    toc_depth: 3
    
- codehilite
- extra
- meta
- abbr
- def_list                      # Les listes de définition.
- attr_list                     # Un peu de CSS et des attributs HTML.
- footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
- admonition                    # Blocs colorés  !!! info "ma remarque"
- pymdownx.snippets
- pymdownx.details              #   qui peuvent se plier/déplier.
- pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
- pymdownx.mark                 # Passage ==surligné==.
- pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
- pymdownx.highlight            # Coloration syntaxique du code
- pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
- pymdownx.snippets             # Inclusion de fichiers externe.
- pymdownx.tabbed               # Volets glissants.  === "Mon volet"
- pymdownx.superfences          # Imbrication de blocs.
- pymdownx.caret
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.tilde

- pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
    custom_checkbox:    false   #   avec cases d'origine
    clickable_checkbox: true    #   et cliquables.
- pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
    separator: "\uff0b"
- pymdownx.emoji:               # Émojis  :boom:
    emoji_index:     !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.magiclink:
    repo_url_shorthand: true
    user: squidfunk
    repo: mkdocs-material
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true

plugins:
- search:
    separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
- minify:
    minify_html: true
- awesome-pages:
    collapse_single_pages: true
- tags:
    tags_file: tags.md
- git-revision-date-localized:
    enable_creation_date: true
    fallback_to_build_date: true
# pour exposer les varaibles défini dans extra. Par defaut un certain nombre de variables sont accesible(config.*, page.*, navigation.*, environment.*, git.*), mais pas les extras. 
#IL doit etre possitionné apres le plugin awesome-pages (The plugin "macros" might not work correctly when placed before awesome-pages in the list of plugins.)
- macros

# Customization
extra:
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
    Linux: linux
  annotate:
    json: [.s2]
  #analytics:
  #  provider: google
  #  property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/solid/paper-plane
      name: Me contacter par email
      link: mailto:adoucheali@yahoo.fr
    - icon: fontawesome/brands/github
      name: Mon compte github
      link: https://github.com/AdoucheAli/      
    - icon: fontawesome/brands/linkedin
      name: Me contacter sur linkedin
      link: https://www.linkedin.com/in/aliadouche

extra_css:
  - stylesheets/extra.css
